#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_user_index:
    path: /back
    controller: App\Controller\UserController::index

app_user_front:
    path: /user
    controller: App\Controller\UserController::front

search:
    path: /search
    controller: App\Controller\UserController::searchUsers
    methods: ['GET', 'POST']


app_annonce_indexfront:
    path: /front
    controller: App\Controller\AnnonceController::indexfront
    methods: ['GET']

# config/routes.yaml
app_commentaire_new:
    path: '/commentaire/{idAnnonce}/new'
    controller: App\Controller\CommentaireController::new
    methods: ['GET', 'POST']

app_annonce_commentairebypost:
    path: /annonces/{idCommentaire}/afficherCommentaires
    controller: App\Controller\AnnonceController::afficherCommentaires

app_commentaire_commenter_ajax:
    path: /annonces/{idAnnonce}/new-ajax
    controller: App\Controller\CommentaireController::commenterAjax
    methods: ['POST']

app_reactions_like:
    path: '/reactions/like/{id}'
    controller: 'App\Controller\ReactionsController::like'
    methods: ['GET', 'POST']

app_reactions_dislike:
    path: '/reactions/dislike/{id}'
    controller: 'App\Controller\ReactionsController::dislike'
    methods: ['GET', 'POST']

app_mesannonces_index:
    path: /mesannonces
    controller: App\Controller\AnnonceController::front_index
    methods: ['GET']
    
pdf_generator:
    path: /pdf/generator/
    controller: App\Controller\PdfGeneratorController::index

annonce_list:
    path: /annonce/list
    controller: App\Controller\AnnonceController::annonceList


app_evenement_index:
    path: /back/event
    controller: App\Controller\EvenementController::index

# Définition de la route par défaut
app:
    path: /evenement
    controller: App\Controller\EvenementController::front


produits_index:
    path: /
    controller: App\Controller\ProduitController::index

favoris_toggle:
    path: '/favoris/toggle'
    controller: App\Controller\FavorisController::toggle
    methods: [POST]

app_produit_favoribyuser:
    path: /produit/favoribyuser
    controller: App\Controller\ProduitController::favoribyuser
    methods: GET    

app_api_annonces:
    path: /api/annonces
    methods: GET
    controller: App\Controller\ApiAnnonceController::getAnnonces

app_api_annonces_add:
    path: /api/annonces/add
    methods: ['GET', 'POST']
    controller: App\Controller\ApiAnnonceController::addAnnonce    


   